### ISSUE TITLE
ng4 highlight works on ngAfterViewChecked hook but not on ngAfterViewInit

### ISSUE THREAD

**Issue by daggerok** [JayChase/angular2-highlight-js#13]
Hello, for some reasons I wasn't able to highlight a code using ngAfterViewInit hook. 
After few tries I was succeed with AfterViewChecked interface.

[here is a code sample](https://github.com/daggerok/ng4-cli-materialize-highlight/blob/master/src/app/highlight/highlight.component.ts)

if it's expected behavior, then maybe better update documentation.

---
BR, Max

**Comment by JayChase** [comment]
Thanks for the update will have a look.
