### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by sergey-morenets** [JayChase/angular2-highlight-js#14]
Hi

Do you have plans to support AOT compilation? I use ngx-filter dependency and received the following message during rollup:

'HighlightJsService' is not exported by 'node_modules\angular2-highlight-js\lib\highlight-js.service.js'

https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

Thanks

**Comment by JayChase** [comment]
I am not sure what the rollup issue is as I don't use it myself. The package supports AOT compilation, if you use angular-cli it will build AOT or you can use ngc directly. If you find anything that needs changing send me a pull request or let me know the details and I will put out a new version. Thanks.
